// <auto-generated />
using System;
using App.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181217175856_paycheks")]
    partial class paycheks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmpId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Location")
                        .IsRequired();

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("App.Entities.EmployeeSalary", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BaseSalary");

                    b.Property<double>("Deduction401");

                    b.Property<double>("DeductionDental");

                    b.Property<double>("DeductionMedicare");

                    b.Property<Guid>("EmpId");

                    b.HasKey("id");

                    b.HasIndex("EmpId")
                        .IsUnique();

                    b.ToTable("EmployeeSalaries");
                });

            modelBuilder.Entity("App.Entities.PayChecks", b =>
                {
                    b.Property<Guid>("TxnId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BaseSalary");

                    b.Property<double>("Deduction401");

                    b.Property<double>("DeductionDental");

                    b.Property<double>("DeductionMedicare");

                    b.Property<Guid>("EmpId");

                    b.Property<double>("FederalTax");

                    b.Property<double>("StateTax");

                    b.Property<double>("TakeHomSalary");

                    b.Property<DateTimeOffset>("TxnDate");

                    b.HasKey("TxnId");

                    b.HasIndex("EmpId");

                    b.ToTable("PayChecks");
                });

            modelBuilder.Entity("App.Entities.EmployeeSalary", b =>
                {
                    b.HasOne("App.Entities.Employee", "Employee")
                        .WithOne("EmployeeSalary")
                        .HasForeignKey("App.Entities.EmployeeSalary", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("App.Entities.PayChecks", b =>
                {
                    b.HasOne("App.Entities.Employee", "Employee")
                        .WithMany("IssuedPayChecks")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
